FROM node:18-alpine

WORKDIR /app

#copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# default command to run the application
CMD ["npm", "run", "start:dev"]