FROM node:18-alpine

WORKDIR /app

COPY package.json ./

# install dependencies
RUN npm install

#copy all files
COPY . .

# default command to run the application
CMD ["npm" ,"run" ,"start:dev"]